### ISSUE TITLE
Bring git.spdx.org and GitHub together

### ISSUE THREAD

**Issue by kemitchell** [goneall/SPDX-Tools#6]
@goneall, I notice that the repository of spdx-tools on GitHub is only slightly behind the one on git.spdx.org. Would you mind adding me to the @spdx organization on GitHub? I will:

1. clone `git.spdx.org:spdx-tools` to `github.com:spdx/spdx-tools`
2. send pull requests to bring my work on JSON into the project

That way I can cross-reference my pull requests to the various package managers to a pull request on an spdx github organization repository. If the various packaging maintainers ever revisit SPDX, they'll appreciate having that history.

**Comment by goneall** [comment]
I believe the githumb.com:spdx/spdx-tools is automatically sync'd to git.spdx.org, so I don't think you need to clone it.

This is a good place to do the pull requests.

I'll go ahead and add you to the @spdx organization.

**Comment by kemitchell** [comment]
You're right about the synchronization! I was looking at goneall/spdx-tools.

Thanks for adding me to the org. I will recreate my fork of the repo
from spdx/tools and PR from there.

On Fri, May 15, 2015 at 01:41:53PM -0700, goneall wrote:
> I believe the githumb.com:spdx/spdx-tools is automatically sync'd to git.spdx.org, so I don't think you need to clone it.
> 
> This is a good place to do the pull requests.
> 
> I'll go ahead and add you to the @spdx organization.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/goneall/SPDX-Tools/issues/6#issuecomment-102521837

-- 
Kyle Mitchell, attorney
San Francisco, California
+1 (415) 864 - 9913

**Comment by goneall** [comment]
Just added - I created a new team - contributor - let me know if you have enough access to enough repos.

**Comment by goneall** [comment]
One more request - If you could include on your pull request a comment that the modifications are being made available under the terms of the Apache License version 2.0.

Thanks for taking this on!
